[Interface]
PrivateKey = OKnDm83CCVs9whofjU8iLbDPnCufi5L+0Z73H8MgRlQ=
Address = 10.10.10.2/32
DNS = 10.10.10.1, 1.1.1.1

[Peer]
PublicKey = SDzshxmtcYD6Y2dY6Yqbz+9Ba6qeskhOIn5uSICEezo=
Endpoint = 154.26.158.68:51821
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25