#!/bin/bash
set -euo pipefail

# =============================================================================
# MCP Bundle Automated Maintenance Deployment
# =============================================================================
# Deploy comprehensive self-healing and maintenance automation across all VMs
#
# Features:
# - Self-healing service monitors (10s intervals)
# - Auto-restart failed services (max 3 attempts, 5min cooldown)
# - Prometheus metrics integration
# - Scheduled maintenance tasks:
#   - Daily: Log cleanup, disk space monitoring, metrics collection
#   - Weekly: Database VACUUM, security update checks
#   - Monthly: Full optimization, backup verification
# - Systemd service and timer management
#
# Usage: ./deploy-maintenance.sh [options]
# Options:
#   --vm <vm>       Deploy to specific VM only (vmi01, vmi02d, vmi03, all)
#   --service-only  Deploy only service monitors
#   --cron-only     Deploy only scheduled tasks
#   --dry-run       Show what would be deployed without making changes
# =============================================================================

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m' # No Color
readonly BOLD='\033[1m'

# VM Configuration
declare -A VMS=(
    ["vmi01"]="46.250.243.123"
    ["vmi02d"]="46.250.241.70"
    ["vmi03"]="154.26.158.31"
)

declare -A VM_SERVICES=(
    ["vmi01"]="postgresql,mcp-orchestrator,perplexity-mcp,itjsst-mcp,redis-server,pgbouncer"
    ["vmi02d"]="postgresql,mcp-storage"
    ["vmi03"]="haproxy,prometheus,grafana,nginx,pihole-FTL"
)

# Configuration
TARGET_VM="all"
SERVICE_ONLY=false
CRON_ONLY=false
DRY_RUN=false
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DEPLOY_DIR="/opt/mcp/maintenance"
LOG_DIR="/var/log/mcp"

# Monitoring configuration
readonly HEALTH_CHECK_INTERVAL=10
readonly MAX_RESTART_ATTEMPTS=3
readonly RESTART_COOLDOWN=300  # 5 minutes
readonly PROMETHEUS_PUSHGATEWAY="http://154.26.158.31:9091"

# =============================================================================
# Utility Functions
# =============================================================================

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $*"
}

log_error() {
    echo -e "${RED}[✗]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[!]${NC} $*"
}

log_header() {
    echo -e "\n${BOLD}${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${CYAN}$*${NC}"
    echo -e "${BOLD}${CYAN}═══════════════════════════════════════════════════════════════${NC}\n"
}

execute_on_vm() {
    local vm_ip=$1
    shift
    local cmd="$*"

    if [ "$DRY_RUN" = true ]; then
        log "[DRY-RUN] Would execute on $vm_ip: $cmd"
        return 0
    fi

    ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no "root@${vm_ip}" "$cmd"
}

copy_to_vm() {
    local vm_ip=$1
    local local_file=$2
    local remote_file=$3

    if [ "$DRY_RUN" = true ]; then
        log "[DRY-RUN] Would copy $local_file to $vm_ip:$remote_file"
        return 0
    fi

    scp -o ConnectTimeout=10 -o StrictHostKeyChecking=no "$local_file" "root@${vm_ip}:${remote_file}"
}

# =============================================================================
# Self-Healing Service Monitor Generator
# =============================================================================

generate_service_monitor() {
    local vm_name=$1
    local services=$2

    cat << 'EOF'
#!/bin/bash
# =============================================================================
# MCP Self-Healing Service Monitor
# =============================================================================
# Automatically monitors and restarts failed services with intelligent cooldown
# Generated by deploy-maintenance.sh
# =============================================================================

set -euo pipefail

readonly STATE_DIR="/var/lib/mcp/service-monitor"
readonly LOG_FILE="/var/log/mcp/service-monitor.log"
readonly MAX_ATTEMPTS=3
readonly COOLDOWN_SECONDS=300
readonly METRICS_FILE="/var/lib/node_exporter/textfile_collector/mcp_services.prom"

# Service list
EOF

    echo "readonly SERVICES=($(echo "$services" | sed 's/,/ /g'))" >> /tmp/service-monitor-$$.sh
    cat /tmp/service-monitor-$$.sh

    cat << 'EOF'

# Initialize state directory
mkdir -p "$STATE_DIR"
mkdir -p "$(dirname "$LOG_FILE")"
mkdir -p "$(dirname "$METRICS_FILE")"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Get restart count for service
get_restart_count() {
    local service=$1
    local count_file="${STATE_DIR}/${service}.count"

    if [ -f "$count_file" ]; then
        cat "$count_file"
    else
        echo "0"
    fi
}

# Increment restart count
increment_restart_count() {
    local service=$1
    local count_file="${STATE_DIR}/${service}.count"
    local count=$(get_restart_count "$service")

    echo $((count + 1)) > "$count_file"
}

# Reset restart count
reset_restart_count() {
    local service=$1
    local count_file="${STATE_DIR}/${service}.count"

    echo "0" > "$count_file"
}

# Check if service is in cooldown
is_in_cooldown() {
    local service=$1
    local cooldown_file="${STATE_DIR}/${service}.cooldown"

    if [ -f "$cooldown_file" ]; then
        local cooldown_until=$(cat "$cooldown_file")
        local now=$(date +%s)

        if [ "$now" -lt "$cooldown_until" ]; then
            local remaining=$((cooldown_until - now))
            log "Service $service is in cooldown for $remaining more seconds"
            return 0
        else
            rm -f "$cooldown_file"
            return 1
        fi
    fi

    return 1
}

# Set cooldown period
set_cooldown() {
    local service=$1
    local cooldown_file="${STATE_DIR}/${service}.cooldown"
    local cooldown_until=$(($(date +%s) + COOLDOWN_SECONDS))

    echo "$cooldown_until" > "$cooldown_file"
    log "Service $service entering cooldown until $(date -d @$cooldown_until 2>/dev/null || date -r $cooldown_until)"
}

# Update Prometheus metrics
update_metrics() {
    local service=$1
    local status=$2
    local restarts=$(get_restart_count "$service")

    # Create metrics in Prometheus format
    {
        echo "# HELP mcp_service_status Service status (1=running, 0=stopped)"
        echo "# TYPE mcp_service_status gauge"
        echo "mcp_service_status{service=\"$service\"} $status"
        echo ""
        echo "# HELP mcp_service_restarts_total Total number of service restarts"
        echo "# TYPE mcp_service_restarts_total counter"
        echo "mcp_service_restarts_total{service=\"$service\"} $restarts"
    } >> "$METRICS_FILE.tmp"
}

# Check and heal service
check_service() {
    local service=$1

    # Check if service is active
    if systemctl is-active --quiet "$service"; then
        # Service is running
        reset_restart_count "$service"
        update_metrics "$service" 1
        return 0
    else
        # Service is not running
        log "Service $service is not running"
        update_metrics "$service" 0

        # Check if in cooldown
        if is_in_cooldown "$service"; then
            log "Service $service in cooldown, skipping restart"
            return 1
        fi

        # Check restart count
        local restart_count=$(get_restart_count "$service")

        if [ "$restart_count" -ge "$MAX_ATTEMPTS" ]; then
            log "Service $service has exceeded maximum restart attempts ($MAX_ATTEMPTS)"
            set_cooldown "$service"
            reset_restart_count "$service"

            # Send alert
            logger -p daemon.crit "MCP: Service $service failed to start after $MAX_ATTEMPTS attempts"

            return 1
        fi

        # Attempt restart
        log "Attempting to restart $service (attempt $((restart_count + 1))/$MAX_ATTEMPTS)"

        if systemctl restart "$service"; then
            log "Successfully restarted $service"
            increment_restart_count "$service"

            # Wait a bit and verify it stayed up
            sleep 5

            if systemctl is-active --quiet "$service"; then
                log "Service $service is stable after restart"
                update_metrics "$service" 1
                return 0
            else
                log "Service $service failed to stay running"
                update_metrics "$service" 0
                return 1
            fi
        else
            log "Failed to restart $service"
            increment_restart_count "$service"
            update_metrics "$service" 0
            return 1
        fi
    fi
}

# Main monitoring loop
main() {
    log "Starting MCP service monitor"

    # Initialize metrics file
    : > "$METRICS_FILE.tmp"

    # Check all services
    local failed_services=0

    for service in "${SERVICES[@]}"; do
        if ! check_service "$service"; then
            ((failed_services++)) || true
        fi
    done

    # Finalize metrics
    mv "$METRICS_FILE.tmp" "$METRICS_FILE"

    # Overall health metric
    {
        echo "# HELP mcp_service_monitor_healthy Overall health check (1=healthy, 0=issues)"
        echo "# TYPE mcp_service_monitor_healthy gauge"
        if [ "$failed_services" -eq 0 ]; then
            echo "mcp_service_monitor_healthy 1"
        else
            echo "mcp_service_monitor_healthy 0"
        fi
        echo ""
        echo "# HELP mcp_service_monitor_failed_services Number of failed services"
        echo "# TYPE mcp_service_monitor_failed_services gauge"
        echo "mcp_service_monitor_failed_services $failed_services"
    } >> "$METRICS_FILE"

    if [ "$failed_services" -gt 0 ]; then
        log "Health check completed with $failed_services failed service(s)"
        exit 1
    else
        log "All services healthy"
        exit 0
    fi
}

main "$@"
EOF

    rm -f /tmp/service-monitor-$$.sh
}

# =============================================================================
# Daily Maintenance Script Generator
# =============================================================================

generate_daily_maintenance() {
    cat << 'EOF'
#!/bin/bash
# =============================================================================
# MCP Daily Maintenance Tasks
# =============================================================================
# - Log rotation and cleanup
# - Disk space monitoring
# - Metrics collection
# - Service health verification
# =============================================================================

set -euo pipefail

readonly LOG_DIR="/var/log/mcp"
readonly LOG_RETENTION_DAYS=30
readonly DISK_WARNING_THRESHOLD=80
readonly DISK_CRITICAL_THRESHOLD=90
readonly METRICS_FILE="/var/lib/node_exporter/textfile_collector/mcp_daily_maintenance.prom"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_DIR}/daily-maintenance.log"
}

# Clean old logs
cleanup_logs() {
    log "Cleaning logs older than $LOG_RETENTION_DAYS days..."

    local deleted_count=0

    # Clean MCP logs
    if [ -d "$LOG_DIR" ]; then
        deleted_count=$(find "$LOG_DIR" -name "*.log" -type f -mtime +$LOG_RETENTION_DAYS -delete -print | wc -l)
        log "Deleted $deleted_count old MCP log files"
    fi

    # Clean journald
    journalctl --vacuum-time=${LOG_RETENTION_DAYS}d >/dev/null 2>&1 || true

    # Clean old compressed logs
    find /var/log -name "*.gz" -type f -mtime +$LOG_RETENTION_DAYS -delete 2>/dev/null || true

    log "Log cleanup completed"
}

# Check disk space
check_disk_space() {
    log "Checking disk space..."

    local partitions=("/" "/var" "/opt" "/mnt/storage" "/tmp")
    local warning_count=0
    local critical_count=0

    for partition in "${partitions[@]}"; do
        if ! mountpoint -q "$partition" 2>/dev/null && [ "$partition" != "/" ]; then
            continue
        fi

        local usage=$(df -h "$partition" | tail -1 | awk '{print $5}' | sed 's/%//')
        local available=$(df -h "$partition" | tail -1 | awk '{print $4}')

        log "Partition $partition: ${usage}% used, ${available} available"

        # Update metrics
        echo "mcp_disk_usage_percent{partition=\"$partition\"} $usage" >> "$METRICS_FILE.tmp"

        if [ "$usage" -ge "$DISK_CRITICAL_THRESHOLD" ]; then
            log "CRITICAL: Partition $partition is ${usage}% full"
            logger -p daemon.crit "MCP: Disk space critical on $partition (${usage}% used)"
            ((critical_count++)) || true
        elif [ "$usage" -ge "$DISK_WARNING_THRESHOLD" ]; then
            log "WARNING: Partition $partition is ${usage}% full"
            logger -p daemon.warning "MCP: Disk space warning on $partition (${usage}% used)"
            ((warning_count++)) || true
        fi
    done

    # Overall disk health metric
    if [ "$critical_count" -gt 0 ]; then
        echo "mcp_disk_health 0" >> "$METRICS_FILE.tmp"
    elif [ "$warning_count" -gt 0 ]; then
        echo "mcp_disk_health 1" >> "$METRICS_FILE.tmp"
    else
        echo "mcp_disk_health 2" >> "$METRICS_FILE.tmp"
    fi

    log "Disk space check completed"
}

# Collect system metrics
collect_metrics() {
    log "Collecting system metrics..."

    mkdir -p "$(dirname "$METRICS_FILE")"
    : > "$METRICS_FILE.tmp"

    # CPU load
    local load1=$(uptime | awk -F'load average:' '{print $2}' | awk -F',' '{print $1}' | xargs)
    echo "mcp_system_load1 $load1" >> "$METRICS_FILE.tmp"

    # Memory usage
    local mem_total=$(free -b | awk '/Mem:/ {print $2}')
    local mem_used=$(free -b | awk '/Mem:/ {print $3}')
    local mem_percent=$((mem_used * 100 / mem_total))
    echo "mcp_memory_usage_percent $mem_percent" >> "$METRICS_FILE.tmp"

    # Process count
    local process_count=$(ps aux | wc -l)
    echo "mcp_process_count $process_count" >> "$METRICS_FILE.tmp"

    # Check disk space (adds to metrics)
    check_disk_space

    # Finalize metrics
    {
        echo "# HELP mcp_daily_maintenance_timestamp Unix timestamp of last daily maintenance"
        echo "# TYPE mcp_daily_maintenance_timestamp gauge"
        echo "mcp_daily_maintenance_timestamp $(date +%s)"
    } >> "$METRICS_FILE.tmp"

    mv "$METRICS_FILE.tmp" "$METRICS_FILE"

    log "Metrics collection completed"
}

# Verify service health
verify_services() {
    log "Verifying service health..."

    local failed_services=$(systemctl list-units --state=failed --no-pager --no-legend | wc -l)

    if [ "$failed_services" -gt 0 ]; then
        log "WARNING: $failed_services failed service(s) detected"
        systemctl list-units --state=failed --no-pager | tee -a "${LOG_DIR}/daily-maintenance.log"
    else
        log "All services operational"
    fi
}

# Main execution
main() {
    log "Starting daily maintenance tasks"

    cleanup_logs
    collect_metrics
    verify_services

    log "Daily maintenance completed successfully"
}

main "$@"
EOF
}

# =============================================================================
# Weekly Maintenance Script Generator
# =============================================================================

generate_weekly_maintenance() {
    cat << 'EOF'
#!/bin/bash
# =============================================================================
# MCP Weekly Maintenance Tasks
# =============================================================================
# - Database VACUUM and optimization
# - Security update checks
# - Certificate expiration checks
# - Backup verification
# =============================================================================

set -euo pipefail

readonly LOG_DIR="/var/log/mcp"
readonly CERT_WARNING_DAYS=30

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_DIR}/weekly-maintenance.log"
}

# Database maintenance (for database VMs)
database_maintenance() {
    if ! systemctl is-active --quiet postgresql; then
        log "PostgreSQL not running on this VM, skipping database maintenance"
        return 0
    fi

    log "Starting database maintenance..."

    # VACUUM all databases
    log "Running VACUUM ANALYZE on all databases..."

    sudo -u postgres psql -c "SELECT datname FROM pg_database WHERE datistemplate = false;" -t | while read -r dbname; do
        dbname=$(echo "$dbname" | xargs)
        [ -z "$dbname" ] && continue

        log "VACUUM ANALYZE on database: $dbname"
        sudo -u postgres psql -d "$dbname" -c "VACUUM ANALYZE;" 2>&1 | tee -a "${LOG_DIR}/weekly-maintenance.log"
    done

    # Reindex critical tables
    log "Reindexing system catalogs..."
    sudo -u postgres psql -d postgres -c "REINDEX SYSTEM postgres;" 2>&1 | tee -a "${LOG_DIR}/weekly-maintenance.log"

    # Update statistics
    log "Updating planner statistics..."
    sudo -u postgres psql -d postgres -c "ANALYZE;" 2>&1 | tee -a "${LOG_DIR}/weekly-maintenance.log"

    # Check for bloated tables
    log "Checking for table bloat..."
    sudo -u postgres psql -d postgres << 'SQL' | tee -a "${LOG_DIR}/weekly-maintenance.log"
SELECT
    schemaname,
    tablename,
    pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) AS size
FROM pg_tables
WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC
LIMIT 10;
SQL

    log "Database maintenance completed"
}

# Check for security updates
check_security_updates() {
    log "Checking for security updates..."

    if command -v apt-get &> /dev/null; then
        # Debian/Ubuntu
        apt-get update -qq
        local security_updates=$(apt-get upgrade -s | grep -i security | wc -l)

        if [ "$security_updates" -gt 0 ]; then
            log "WARNING: $security_updates security updates available"
            apt-get upgrade -s | grep -i security | tee -a "${LOG_DIR}/weekly-maintenance.log"
            logger -p daemon.warning "MCP: $security_updates security updates available"
        else
            log "System is up to date with security patches"
        fi

    elif command -v yum &> /dev/null; then
        # RHEL/CentOS
        local security_updates=$(yum updateinfo list security 2>/dev/null | grep -c 'security' || echo 0)

        if [ "$security_updates" -gt 0 ]; then
            log "WARNING: $security_updates security updates available"
            yum updateinfo list security | tee -a "${LOG_DIR}/weekly-maintenance.log"
            logger -p daemon.warning "MCP: $security_updates security updates available"
        else
            log "System is up to date with security patches"
        fi
    fi
}

# Check SSL certificate expiration
check_certificates() {
    log "Checking SSL certificate expiration..."

    local cert_dirs=("/etc/ssl/certs" "/etc/nginx/ssl" "/etc/letsencrypt/live")
    local warning_count=0

    for cert_dir in "${cert_dirs[@]}"; do
        if [ ! -d "$cert_dir" ]; then
            continue
        fi

        find "$cert_dir" -name "*.crt" -o -name "*.pem" 2>/dev/null | while read -r cert; do
            if openssl x509 -in "$cert" -noout -text &> /dev/null; then
                local expiry_date=$(openssl x509 -in "$cert" -noout -enddate | cut -d= -f2)
                local expiry_epoch=$(date -d "$expiry_date" +%s 2>/dev/null || date -j -f "%b %d %H:%M:%S %Y %Z" "$expiry_date" +%s 2>/dev/null || echo 0)
                local now_epoch=$(date +%s)
                local days_until_expiry=$(( (expiry_epoch - now_epoch) / 86400 ))

                if [ "$days_until_expiry" -lt "$CERT_WARNING_DAYS" ] && [ "$days_until_expiry" -gt 0 ]; then
                    log "WARNING: Certificate $cert expires in $days_until_expiry days"
                    logger -p daemon.warning "MCP: SSL certificate $cert expires in $days_until_expiry days"
                    ((warning_count++)) || true
                elif [ "$days_until_expiry" -le 0 ]; then
                    log "CRITICAL: Certificate $cert has EXPIRED"
                    logger -p daemon.crit "MCP: SSL certificate $cert has expired"
                    ((warning_count++)) || true
                fi
            fi
        done
    done

    if [ "$warning_count" -eq 0 ]; then
        log "All certificates valid for at least $CERT_WARNING_DAYS days"
    fi
}

# Verify backup health
verify_backups() {
    log "Verifying backup health..."

    local backup_dir="/mnt/storage/backups"

    if [ ! -d "$backup_dir" ]; then
        log "Backup directory not found on this VM"
        return 0
    fi

    # Check latest backup age
    local latest_backup=$(find "$backup_dir" -type f -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2)

    if [ -n "$latest_backup" ]; then
        local age=$(( $(date +%s) - $(stat -c %Y "$latest_backup" 2>/dev/null || stat -f %m "$latest_backup") ))
        local age_hours=$((age / 3600))

        log "Latest backup: $(basename "$latest_backup"), age: ${age_hours}h"

        if [ "$age_hours" -gt 48 ]; then
            log "WARNING: Latest backup is more than 48 hours old"
            logger -p daemon.warning "MCP: Latest backup is ${age_hours} hours old"
        else
            log "Backup freshness OK"
        fi
    else
        log "WARNING: No backups found"
        logger -p daemon.warning "MCP: No backups found in $backup_dir"
    fi

    # Check backup disk usage
    local backup_usage=$(df -h "$backup_dir" | tail -1 | awk '{print $5}' | sed 's/%//')
    log "Backup storage usage: ${backup_usage}%"

    if [ "$backup_usage" -gt 85 ]; then
        log "WARNING: Backup storage usage is high (${backup_usage}%)"
        logger -p daemon.warning "MCP: Backup storage usage is ${backup_usage}%"
    fi
}

# Main execution
main() {
    log "Starting weekly maintenance tasks"

    database_maintenance
    check_security_updates
    check_certificates
    verify_backups

    log "Weekly maintenance completed successfully"
}

main "$@"
EOF
}

# =============================================================================
# Monthly Maintenance Script Generator
# =============================================================================

generate_monthly_maintenance() {
    cat << 'EOF'
#!/bin/bash
# =============================================================================
# MCP Monthly Maintenance Tasks
# =============================================================================
# - Full database optimization
# - Comprehensive backup verification
# - System audit and reporting
# - Performance analysis
# =============================================================================

set -euo pipefail

readonly LOG_DIR="/var/log/mcp"
readonly REPORT_DIR="/var/lib/mcp/reports"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_DIR}/monthly-maintenance.log"
}

# Full database optimization
optimize_database() {
    if ! systemctl is-active --quiet postgresql; then
        log "PostgreSQL not running on this VM, skipping database optimization"
        return 0
    fi

    log "Starting full database optimization..."

    # Full VACUUM
    log "Running VACUUM FULL on all databases (this may take a while)..."
    sudo -u postgres psql -c "SELECT datname FROM pg_database WHERE datistemplate = false;" -t | while read -r dbname; do
        dbname=$(echo "$dbname" | xargs)
        [ -z "$dbname" ] && continue

        log "VACUUM FULL on database: $dbname"
        sudo -u postgres psql -d "$dbname" -c "VACUUM FULL;" 2>&1 | tee -a "${LOG_DIR}/monthly-maintenance.log" || true
    done

    # Reindex all databases
    log "Reindexing all databases..."
    sudo -u postgres psql -c "SELECT datname FROM pg_database WHERE datistemplate = false;" -t | while read -r dbname; do
        dbname=$(echo "$dbname" | xargs)
        [ -z "$dbname" ] && continue

        log "REINDEX on database: $dbname"
        sudo -u postgres psql -d "$dbname" -c "REINDEX DATABASE $dbname;" 2>&1 | tee -a "${LOG_DIR}/monthly-maintenance.log" || true
    done

    log "Database optimization completed"
}

# Comprehensive system audit
system_audit() {
    log "Performing comprehensive system audit..."

    mkdir -p "$REPORT_DIR"
    local report_file="${REPORT_DIR}/monthly-audit-$(date +%Y%m).txt"

    {
        echo "==================================="
        echo "MCP Monthly System Audit Report"
        echo "Generated: $(date)"
        echo "==================================="
        echo ""

        echo "System Information:"
        echo "-----------------------------------"
        uname -a
        echo ""
        lsb_release -a 2>/dev/null || cat /etc/os-release
        echo ""

        echo "Uptime:"
        echo "-----------------------------------"
        uptime
        echo ""

        echo "Disk Usage:"
        echo "-----------------------------------"
        df -h
        echo ""

        echo "Memory Usage:"
        echo "-----------------------------------"
        free -h
        echo ""

        echo "Top Processes by Memory:"
        echo "-----------------------------------"
        ps aux --sort=-%mem | head -20
        echo ""

        echo "Top Processes by CPU:"
        echo "-----------------------------------"
        ps aux --sort=-%cpu | head -20
        echo ""

        echo "Service Status:"
        echo "-----------------------------------"
        systemctl list-units --type=service --state=running --no-pager
        echo ""

        echo "Failed Services:"
        echo "-----------------------------------"
        systemctl list-units --type=service --state=failed --no-pager
        echo ""

        echo "Network Connections:"
        echo "-----------------------------------"
        ss -tuln
        echo ""

        echo "Security Updates:"
        echo "-----------------------------------"
        if command -v apt-get &> /dev/null; then
            apt-get update -qq
            apt-get upgrade -s | grep -i security || echo "No security updates"
        elif command -v yum &> /dev/null; then
            yum updateinfo list security 2>/dev/null || echo "No security updates"
        fi
        echo ""

    } > "$report_file"

    log "System audit report saved to: $report_file"
}

# Performance analysis
performance_analysis() {
    log "Performing performance analysis..."

    local perf_report="${REPORT_DIR}/performance-$(date +%Y%m).txt"

    {
        echo "==================================="
        echo "MCP Performance Analysis Report"
        echo "Generated: $(date)"
        echo "==================================="
        echo ""

        echo "I/O Statistics:"
        echo "-----------------------------------"
        iostat -x 1 5 2>/dev/null || echo "iostat not available"
        echo ""

        echo "Network Statistics:"
        echo "-----------------------------------"
        netstat -s 2>/dev/null || ss -s
        echo ""

        if systemctl is-active --quiet postgresql; then
            echo "Database Statistics:"
            echo "-----------------------------------"
            sudo -u postgres psql -d postgres << 'SQL'
SELECT
    datname,
    numbackends as connections,
    xact_commit as commits,
    xact_rollback as rollbacks,
    blks_read as blocks_read,
    blks_hit as blocks_hit,
    tup_returned as tuples_returned,
    tup_fetched as tuples_fetched,
    tup_inserted as tuples_inserted,
    tup_updated as tuples_updated,
    tup_deleted as tuples_deleted
FROM pg_stat_database
WHERE datname NOT IN ('template0', 'template1');
SQL
            echo ""

            echo "Slow Queries (if pg_stat_statements enabled):"
            echo "-----------------------------------"
            sudo -u postgres psql -d postgres -c "SELECT query, calls, total_time, mean_time FROM pg_stat_statements ORDER BY mean_time DESC LIMIT 10;" 2>/dev/null || echo "pg_stat_statements not enabled"
            echo ""
        fi

    } > "$perf_report"

    log "Performance report saved to: $perf_report"
}

# Backup verification
verify_backups() {
    log "Running backup verification..."

    if [ -x "/opt/mcp/deployment/tests/backup-validation-tests.sh" ]; then
        /opt/mcp/deployment/tests/backup-validation-tests.sh --latest 2>&1 | tee -a "${LOG_DIR}/monthly-maintenance.log"
    else
        log "Backup validation script not found, skipping"
    fi
}

# Main execution
main() {
    log "Starting monthly maintenance tasks"

    optimize_database
    system_audit
    performance_analysis
    verify_backups

    log "Monthly maintenance completed successfully"
    log "Reports available in: $REPORT_DIR"
}

main "$@"
EOF
}

# =============================================================================
# Systemd Service and Timer Generators
# =============================================================================

generate_service_monitor_systemd() {
    cat << EOF
[Unit]
Description=MCP Self-Healing Service Monitor
After=network.target

[Service]
Type=oneshot
ExecStart=${DEPLOY_DIR}/service-monitor.sh
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mcp-service-monitor

[Install]
WantedBy=multi-user.target
EOF
}

generate_service_monitor_timer() {
    cat << EOF
[Unit]
Description=MCP Service Monitor Timer (every ${HEALTH_CHECK_INTERVAL}s)

[Timer]
OnBootSec=30s
OnUnitActiveSec=${HEALTH_CHECK_INTERVAL}s
AccuracySec=1s

[Install]
WantedBy=timers.target
EOF
}

generate_daily_maintenance_timer() {
    cat << EOF
[Unit]
Description=MCP Daily Maintenance Timer

[Timer]
OnCalendar=daily
OnCalendar=*-*-* 02:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
}

generate_weekly_maintenance_timer() {
    cat << EOF
[Unit]
Description=MCP Weekly Maintenance Timer

[Timer]
OnCalendar=weekly
OnCalendar=Sun 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
}

generate_monthly_maintenance_timer() {
    cat << EOF
[Unit]
Description=MCP Monthly Maintenance Timer

[Timer]
OnCalendar=monthly
OnCalendar=*-*-01 04:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
}

generate_maintenance_service() {
    local name=$1
    local script=$2

    cat << EOF
[Unit]
Description=MCP ${name} Maintenance
After=network.target

[Service]
Type=oneshot
ExecStart=${DEPLOY_DIR}/${script}
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mcp-${name}-maintenance

[Install]
WantedBy=multi-user.target
EOF
}

# =============================================================================
# Deployment Functions
# =============================================================================

deploy_to_vm() {
    local vm_name=$1
    local vm_ip=$2

    log_header "Deploying to $vm_name ($vm_ip)"

    # Create directories
    log "Creating deployment directories..."
    execute_on_vm "$vm_ip" "mkdir -p ${DEPLOY_DIR} ${LOG_DIR} /var/lib/mcp/service-monitor /var/lib/mcp/reports /var/lib/node_exporter/textfile_collector"

    # Deploy service monitor
    if [ "$CRON_ONLY" != true ]; then
        log "Deploying self-healing service monitor..."

        local services="${VM_SERVICES[$vm_name]}"
        local monitor_script="/tmp/service-monitor-${vm_name}.sh"

        generate_service_monitor "$vm_name" "$services" > "$monitor_script"
        copy_to_vm "$vm_ip" "$monitor_script" "${DEPLOY_DIR}/service-monitor.sh"
        execute_on_vm "$vm_ip" "chmod +x ${DEPLOY_DIR}/service-monitor.sh"

        # Deploy systemd service and timer
        generate_service_monitor_systemd | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-service-monitor.service"
        generate_service_monitor_timer | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-service-monitor.timer"

        rm -f "$monitor_script"

        log_success "Service monitor deployed"
    fi

    # Deploy scheduled maintenance
    if [ "$SERVICE_ONLY" != true ]; then
        log "Deploying scheduled maintenance tasks..."

        # Daily maintenance
        local daily_script="/tmp/daily-maintenance.sh"
        generate_daily_maintenance > "$daily_script"
        copy_to_vm "$vm_ip" "$daily_script" "${DEPLOY_DIR}/daily-maintenance.sh"
        execute_on_vm "$vm_ip" "chmod +x ${DEPLOY_DIR}/daily-maintenance.sh"
        rm -f "$daily_script"

        generate_maintenance_service "daily" "daily-maintenance.sh" | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-daily-maintenance.service"
        generate_daily_maintenance_timer | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-daily-maintenance.timer"

        # Weekly maintenance
        local weekly_script="/tmp/weekly-maintenance.sh"
        generate_weekly_maintenance > "$weekly_script"
        copy_to_vm "$vm_ip" "$weekly_script" "${DEPLOY_DIR}/weekly-maintenance.sh"
        execute_on_vm "$vm_ip" "chmod +x ${DEPLOY_DIR}/weekly-maintenance.sh"
        rm -f "$weekly_script"

        generate_maintenance_service "weekly" "weekly-maintenance.sh" | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-weekly-maintenance.service"
        generate_weekly_maintenance_timer | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-weekly-maintenance.timer"

        # Monthly maintenance
        local monthly_script="/tmp/monthly-maintenance.sh"
        generate_monthly_maintenance > "$monthly_script"
        copy_to_vm "$vm_ip" "$monthly_script" "${DEPLOY_DIR}/monthly-maintenance.sh"
        execute_on_vm "$vm_ip" "chmod +x ${DEPLOY_DIR}/monthly-maintenance.sh"
        rm -f "$monthly_script"

        generate_maintenance_service "monthly" "monthly-maintenance.sh" | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-monthly-maintenance.service"
        generate_monthly_maintenance_timer | execute_on_vm "$vm_ip" "cat > /etc/systemd/system/mcp-monthly-maintenance.timer"

        log_success "Scheduled maintenance deployed"
    fi

    # Reload systemd and enable services
    if [ "$DRY_RUN" != true ]; then
        log "Enabling and starting services..."

        execute_on_vm "$vm_ip" "systemctl daemon-reload"

        if [ "$CRON_ONLY" != true ]; then
            execute_on_vm "$vm_ip" "systemctl enable --now mcp-service-monitor.timer"
            log_success "Service monitor enabled"
        fi

        if [ "$SERVICE_ONLY" != true ]; then
            execute_on_vm "$vm_ip" "systemctl enable --now mcp-daily-maintenance.timer"
            execute_on_vm "$vm_ip" "systemctl enable --now mcp-weekly-maintenance.timer"
            execute_on_vm "$vm_ip" "systemctl enable --now mcp-monthly-maintenance.timer"
            log_success "Maintenance timers enabled"
        fi

        # Show status
        log "Deployment status:"
        execute_on_vm "$vm_ip" "systemctl list-timers 'mcp-*' --no-pager"
    fi

    log_success "Deployment to $vm_name completed"
}

# =============================================================================
# Main Execution
# =============================================================================

print_usage() {
    cat << EOF
Usage: $0 [options]

Options:
  --vm <vm>       Deploy to specific VM (vmi01, vmi02d, vmi03, all)
  --service-only  Deploy only self-healing service monitors
  --cron-only     Deploy only scheduled maintenance tasks
  --dry-run       Show what would be deployed without making changes
  -h, --help      Show this help message

Examples:
  $0                      # Deploy everything to all VMs
  $0 --vm vmi01           # Deploy to VMI01 only
  $0 --service-only       # Deploy only service monitors
  $0 --dry-run            # Preview deployment without changes

EOF
}

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --vm)
                TARGET_VM="$2"
                if [ "$TARGET_VM" != "all" ] && [ -z "${VMS[$TARGET_VM]:-}" ]; then
                    log_error "Unknown VM '$TARGET_VM'. Valid options: ${!VMS[@]} all"
                    exit 1
                fi
                shift 2
                ;;
            --service-only)
                SERVICE_ONLY=true
                shift
                ;;
            --cron-only)
                CRON_ONLY=true
                shift
                ;;
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            -h|--help)
                print_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                print_usage
                exit 1
                ;;
        esac
    done

    log_header "MCP Automated Maintenance Deployment"
    log "Target: $TARGET_VM"
    log "Service Monitor: $([ "$CRON_ONLY" = true ] && echo "Skip" || echo "Deploy")"
    log "Scheduled Tasks: $([ "$SERVICE_ONLY" = true ] && echo "Skip" || echo "Deploy")"
    log "Dry Run: $DRY_RUN"

    # Deploy to each VM
    for vm_name in "${!VMS[@]}"; do
        if [ "$TARGET_VM" != "all" ] && [ "$TARGET_VM" != "$vm_name" ]; then
            continue
        fi

        vm_ip="${VMS[$vm_name]}"
        deploy_to_vm "$vm_name" "$vm_ip"
    done

    log_header "Deployment Complete"

    if [ "$DRY_RUN" = true ]; then
        log_warning "DRY RUN MODE - No changes were made"
    else
        log_success "All maintenance automation deployed successfully"
        log ""
        log "Deployed components:"
        [ "$CRON_ONLY" != true ] && log "  - Self-healing service monitors (${HEALTH_CHECK_INTERVAL}s interval)"
        [ "$SERVICE_ONLY" != true ] && log "  - Daily maintenance (02:00 every day)"
        [ "$SERVICE_ONLY" != true ] && log "  - Weekly maintenance (03:00 every Sunday)"
        [ "$SERVICE_ONLY" != true ] && log "  - Monthly maintenance (04:00 on 1st of month)"
        log ""
        log "Monitor status with:"
        log "  systemctl list-timers 'mcp-*'"
        log "  journalctl -u mcp-service-monitor -f"
        log "  tail -f ${LOG_DIR}/*.log"
    fi

    exit 0
}

# Run main function
main "$@"
