# WireGuard Client Configuration - ROOT Tunnel
# Full Admin Access to all VMs
[Interface]
Address = 10.0.50.254/24
PrivateKey = kFAbRW7POai9AmzjsaUBjEZKIXhY20FljdshJk5Kplc=
DNS = 1.1.1.1, 8.8.8.8

# VMI01
[Peer]
PublicKey = BFvEfmQ7TFA42MzoRaRP1hhneOYWRl0ypa6/3wBPIXQ=
AllowedIPs = 10.0.50.1/32
Endpoint = 46.250.243.123:51820
PersistentKeepalive = 25

# VMI02D
[Peer]
PublicKey = 4Zks9ApcgrDPeiJ6ZxLXSBOwJ1VblzplTaUw7Hq3gkg=
AllowedIPs = 10.0.50.2/32
Endpoint = 46.250.241.70:51820
PersistentKeepalive = 25

# VMI03
[Peer]
PublicKey = Izmi6x3d0JJ/MhbWIqgLGkTOrvSsZG8CizYHwHiQTTc=
AllowedIPs = 10.0.50.3/32
Endpoint = 154.26.158.31:51820
PersistentKeepalive = 25
