# WireGuard Client Configuration - MCP Tunnel
# Service Mesh Access
[Interface]
Address = 10.0.51.254/24
PrivateKey = kFAbRW7POai9AmzjsaUBjEZKIXhY20FljdshJk5Kplc=
DNS = 1.1.1.1, 8.8.8.8

# VMI01
[Peer]
PublicKey = lJwMcveO0k36hXv81r6fNWFHsteJ3lVhGhfd0EoWViI=
AllowedIPs = 10.0.51.1/32
Endpoint = 46.250.243.123:51821
PersistentKeepalive = 25

# VMI02D
[Peer]
PublicKey = 1u8kuYtyljqjQDL/HOTWUGK1LOIYjmBewKqnH5P6WnM=
AllowedIPs = 10.0.51.2/32
Endpoint = 46.250.241.70:51821
PersistentKeepalive = 25

# VMI03
[Peer]
PublicKey = OfWNDlQgNZgHGES0zAnp9iCo6P6oRMF7dlpOVCawqSo=
AllowedIPs = 10.0.51.3/32
Endpoint = 154.26.158.31:51821
PersistentKeepalive = 25
