# WireGuard Client Configuration - RED Tunnel
# Restricted Network Access
[Interface]
Address = 10.0.52.254/24
PrivateKey = kFAbRW7POai9AmzjsaUBjEZKIXhY20FljdshJk5Kplc=
DNS = 1.1.1.1, 8.8.8.8

# VMI01
[Peer]
PublicKey = pbmbT0lgLJRxuyMk/2DhSco7kxfrYIlHHfOeL2NKKQM=
AllowedIPs = 10.0.52.1/32
Endpoint = 46.250.243.123:51822
PersistentKeepalive = 25

# VMI02D
[Peer]
PublicKey = JjokApgzcEBhbpXDNwPa6aC7Q8AbD6vd+ukWq2YfoQQ=
AllowedIPs = 10.0.52.2/32
Endpoint = 46.250.241.70:51822
PersistentKeepalive = 25

# VMI03
[Peer]
PublicKey = whkW3PQWdIiaOulBc/qlpP5oi0z+TxOvY2xO7VFHZTU=
AllowedIPs = 10.0.52.3/32
Endpoint = 154.26.158.31:51822
PersistentKeepalive = 25
