# WireGuard ROOT Tunnel - VMI01
# Full Admin Access - 10.0.50.0/24
[Interface]
Address = 10.0.50.1/24
ListenPort = 51820
PrivateKey = 4K13sJinKAtOMCAGkklGBkGocMmAb5cLqRopUYbSPE0=
SaveConfig = false

# Security rules
PostUp = iptables -A FORWARD -i wg-root -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-root -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: VMI02D
[Peer]
PublicKey = 4Zks9ApcgrDPeiJ6ZxLXSBOwJ1VblzplTaUw7Hq3gkg=
AllowedIPs = 10.0.50.2/32
Endpoint = 46.250.241.70:51820
PersistentKeepalive = 25

# Peer: VMI03
[Peer]
PublicKey = Izmi6x3d0JJ/MhbWIqgLGkTOrvSsZG8CizYHwHiQTTc=
AllowedIPs = 10.0.50.3/32
Endpoint = 154.26.158.31:51820
PersistentKeepalive = 25
