# WireGuard MCP Tunnel - VMI02D
# Service Mesh - 10.0.51.0/24
[Interface]
Address = 10.0.51.2/24
ListenPort = 51821
PrivateKey = wLOUjIry9n0REoW50b7z/9thS6e214plhOcVWWgssXY=
SaveConfig = false

PostUp = iptables -A FORWARD -i wg-mcp -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-mcp -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: VMI01
[Peer]
PublicKey = lJwMcveO0k36hXv81r6fNWFHsteJ3lVhGhfd0EoWViI=
AllowedIPs = 10.0.51.1/32
Endpoint = 46.250.243.123:51821
PersistentKeepalive = 25

# Peer: VMI03
[Peer]
PublicKey = OfWNDlQgNZgHGES0zAnp9iCo6P6oRMF7dlpOVCawqSo=
AllowedIPs = 10.0.51.3/32
Endpoint = 154.26.158.31:51821
PersistentKeepalive = 25
