# WireGuard MCP Tunnel - VMI01
# Service Mesh - 10.0.51.0/24
[Interface]
Address = 10.0.51.1/24
ListenPort = 51821
PrivateKey = qJxRIhMYYs6ERAkba3sStpeY5+1Px3RnlsI3WaEnY2Y=
SaveConfig = false

PostUp = iptables -A FORWARD -i wg-mcp -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-mcp -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: VMI02D
[Peer]
PublicKey = 1u8kuYtyljqjQDL/HOTWUGK1LOIYjmBewKqnH5P6WnM=
AllowedIPs = 10.0.51.2/32
Endpoint = 46.250.241.70:51821
PersistentKeepalive = 25

# Peer: VMI03
[Peer]
PublicKey = OfWNDlQgNZgHGES0zAnp9iCo6P6oRMF7dlpOVCawqSo=
AllowedIPs = 10.0.51.3/32
Endpoint = 154.26.158.31:51821
PersistentKeepalive = 25
