# WireGuard MCP Tunnel - VMI03
# Service Mesh - 10.0.51.0/24
[Interface]
Address = 10.0.51.3/24
ListenPort = 51821
PrivateKey = uNhLPCkl+9EOeXr+NkyP2tZr0aMHGhvX7x69/pKDc1o=
SaveConfig = false

PostUp = iptables -A FORWARD -i wg-mcp -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-mcp -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: VMI01
[Peer]
PublicKey = lJwMcveO0k36hXv81r6fNWFHsteJ3lVhGhfd0EoWViI=
AllowedIPs = 10.0.51.1/32
Endpoint = 46.250.243.123:51821
PersistentKeepalive = 25

# Peer: VMI02D
[Peer]
PublicKey = 1u8kuYtyljqjQDL/HOTWUGK1LOIYjmBewKqnH5P6WnM=
AllowedIPs = 10.0.51.2/32
Endpoint = 46.250.241.70:51821
PersistentKeepalive = 25
