# WireGuard RED Tunnel - VMI02D
# Restricted Network - 10.0.52.0/24
[Interface]
Address = 10.0.52.2/24
ListenPort = 51822
PrivateKey = 0KzCW2WtOFn/fGpnhpz1cLvahUh8rWkbTrT3yNBS8XI=
SaveConfig = false

PostUp = iptables -A FORWARD -i wg-red -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg-red -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peer: VMI01
[Peer]
PublicKey = pbmbT0lgLJRxuyMk/2DhSco7kxfrYIlHHfOeL2NKKQM=
AllowedIPs = 10.0.52.1/32
Endpoint = 46.250.243.123:51822
PersistentKeepalive = 25

# Peer: VMI03
[Peer]
PublicKey = whkW3PQWdIiaOulBc/qlpP5oi0z+TxOvY2xO7VFHZTU=
AllowedIPs = 10.0.52.3/32
Endpoint = 154.26.158.31:51822
PersistentKeepalive = 25
