[Interface]
PrivateKey = {{PRIVATE_KEY}}
Address = {{IP_ADDRESS}}/32
DNS = {{DNS}}

[Peer]
PublicKey = {{SERVER_PUBLIC_KEY}}
PresharedKey = {{PRESHARED_KEY}}
Endpoint = {{ENDPOINT}}
AllowedIPs = {{ALLOWED_IPS}}
PersistentKeepalive = 25
